account/urls.py
from .views import register,HomePage,logout_user,login
from django .urls import path
app_name = "account"  

urlpatterns = [
    path('',HomePage,name='homepage'),
    path('register/',register,name='register'),
    path("logout/", logout_user, name="logout_user"),
    path('login/',login,name='login'),
]

config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('post/',include('post.urls')),
]
if settings.DEBUG:
    
    urlpatterns+=static(settings.STATIC_URL , document_root = settings.STATICFILES_DIRS)
    urlpatterns+=static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

post/urls.py
# from .views import KvarteraView,saveform,post_list_view,post_detail_view
from .views.post import KvarteraView
from .views.post_list import saveform,post_detail_view,post_list_view
from django .urls import path
from .category_processors import all_categories,all_works
app_name = "post"  

urlpatterns = [
    path('list/',KvarteraView,name='kvarteraview'),
    path("saveform/", saveform, name="saveform"),
    path("list", post_list_view, name="post_list_view"),
    path("category/<slug:category_slug>/", post_list_view, name="post_list_view"),
    path('post-list/<slug:category>/<slug:subcategory>/', post_list_view, name='post_list_view'),
    path("<slug:category_slug>/<slug:product_slug>/", post_detail_view, name="post_detail_view"),
    path('categories/', all_categories, name='categories'),
    path('categories/', all_works, name='all_works'),
]

templates/includes/fotter.html
<!-- ========================= FOOTER ========================= -->
<footer class="section-footer border-top">
	<div class="container">
		<section class="footer-bottom border-top row">
			<div class="col-md-2">
				<p class="text-muted"> &copy 2019 Company name </p>
			</div>
			<div class="col-md-8 text-md-center">
				<span  class="px-2">info@pixsellz.io</span>
				<span  class="px-2">+879-332-9375</span>
				<span  class="px-2">Street name 123, Avanue abc</span>
			</div>
			<div class="col-md-2 text-md-right text-muted">
				<i class="fab fa-lg fa-cc-visa"></i>
				<i class="fab fa-lg fa-cc-paypal"></i>
				<i class="fab fa-lg fa-cc-mastercard"></i>
			</div>
		</section>
	</div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->

templates/includes/header.html
{% load static %}
{% load i18n %}
<header class="section-header">
    <nav class="navbar p-md-0 navbar-expand-sm navbar-light border-bottom">
        <div class="container">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item dropdown">
                     <a href="#" class="nav-link">   English </a>
                    
                </li>
                <li class="nav-item dropdown">
                    <a href="#" class="nav-link"> USD </a>
                </li>
            </ul>
            
                <div class="col-lg  col-md-6 col-sm-12 col">
                    <form mathod="get" action="#" class="search">
                        <div class="input-group w-100">
                            <input type="text" class="form-control" name="q" style="width:60%;" placeholder="Search">

                            <div class="input-group-append">
                                <button class="btn btn-primary" type="submit">
                                    <i class="fa fa-search"></i>
                                </button>
                            </div>
                        </div>
                    </form> <!-- search-wrap .end// -->
                </div> <!-- col.// -->
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop4"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
          
                    
                </div>
                <ul>
                    
                <ul/>
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item dropdown">
                       

                    </li>
                    <li class="nav-item dropdown">
                        <a href="#" class="nav-link"> USD </a>
                    </li>
                </ul>
                <ul class="navbar-nav">
                    <li><a href="#" class="nav-link"> <i class="fa fa-envelope"></i> Email </a></li>
                    <li><a href="#" class="nav-link"> <i class="fa fa-phone"></i> Call us </a></li>
                </ul> <!-- list-inline //  -->
            </div> <!-- navbar-collapse .// -->
        </div> <!-- container //  -->
    </nav>

    <section class="header-main border-bottom">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-2 col-md-3 col-6">
                    <a href="./" class="brand-wrap">
                        <img class="logo" src="{% static './images/Olx.png' %}">
                    </a> <!-- brand-wrap.// -->
                </div>
                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i> Kvarteralar
                        </button>
                        <div class="dropdown-menu">
                            {% for category in categories %}
                            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                            {% endfor %}
                        </div>
                    </div> <!-- category-wrap.// -->
                </div> <!-- col.// -->

                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i>Universitet
                        </button>
                        <div class="dropdown-menu">
                            {% for category in categories %}
                            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                            {% endfor %}
                        </div>
                    </div> <!-- category-wrap.// -->
                </div> <!-- col.// -->

                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i> Talabaga ish
                        </button>
                        <div class="dropdown-menu">
                            {% for category in all_works %}
                            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                            {% endfor %}
                        </div>
                    </div> <!-- category-wrap.// -->
                </div> <!-- col.// -->

                <div class="col-lg col-sm col-md col-6 flex-grow-0">
                    <div class="category-wrap dropdown d-inline-block float-right">
                        <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                            <i class="fa fa-bars"></i>Madaniy xordiq
                        </button>
                        <div class="dropdown-menu">
                            {% for category in categories %}
                            <a class="dropdown-item" href="{{ category.get_absolute_url }}">{{ category.name }}</a>
                            {% endfor %}
                        </div>
                    </div> <!-- category-wrap.// -->
                </div> <!-- col.// -->

               

                
               
               
                <div class="col-lg-3 col-sm-6 col-8 order-2 order-lg-3">
                    <div class="d-flex justify-content-end mb-3 mb-lg-0">
                        <div class="widget-header">
                            {% if user.is_authenticated %}
                                <small class="title text-muted">#</small>
                                <div>
                                    <a href="{% url 'account:logout_user' %}" class="mr-3">Sign out 
                                        <i class="fa fa-sign-out"></i>
                                    </a>
                                    <a href="{% url 'post:kvarteraview' %}">Elon berish
                                        <i class="col order-12"></i>
                                    </a>
                                </div>
                            {% else %}
                                <small class="title text-muted"> Welcome guest!</small>
                                <div>
                                    <a href="{% url 'account:login' %}">Sign in</a> <span class="dark-transp"> | </span>
                                    <a href="{% url 'account:register' %}"> register</a>
                                </div>
                            {% endif %}
                        </div>
                        
                            <div class="icon icon-sm rounded-circle border"><i class="fa fa-shopping-cart"></i></div>
                            <span class="badge badge-pill badge-danger notify">{{counter}}</span>
                        </a>
                    </div> <!-- widgets-wrap.// -->
                </div> <!-- col.// -->
            </div> <!-- row.// -->
         
        </div> <!-- container.// -->
       
    
    </section> <!-- header-main .// -->
  


</header> <!-- section-header.// -->

templates/includes/message.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }}">
            <b>{{ message }}</b>
        </div>
    {% endfor %}
{% endif %}