config/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('account.urls')),
    path('post/',include('post.urls')),
]
if settings.DEBUG:
    
    urlpatterns+=static(settings.STATIC_URL , document_root = settings.STATICFILES_DIRS)
    urlpatterns+=static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

post/urls.py
# from .views import KvarteraView,saveform,post_list_view,post_detail_view
from .views.post import KvarteraView
from .views.post_list import saveform,post_detail_view,post_list_view
from django .urls import path
from .category_processors import all_categories,all_works
app_name = "post"  

urlpatterns = [
    path('list/',KvarteraView,name='kvarteraview'),
    path("saveform/", saveform, name="saveform"),
    path("list", post_list_view, name="post_list_view"),
    path("category/<slug:category_slug>/", post_list_view, name="post_list_view"),
    path('post-list/<slug:category>/<slug:subcategory>/', post_list_view, name='post_list_view'),
    path("<slug:category_slug>/<slug:product_slug>/", post_detail_view, name="post_detail_view"),
    path('categories/', all_categories, name='categories'),
    path('categories/', all_works, name='all_works'),
]

post/models.py
from django.db import models
from account.models import Account
from autoslug import AutoSlugField
from django.urls import reverse
# Create your models here.
from django.contrib.auth.models import User
from .file_renamer import PathAndRename
class Category(models.Model):
    name = models.CharField(max_length=100,unique=True)
    slug = AutoSlugField(populate_from='name', unique=True,max_length=100)
    class Meta:
        verbose_name = ("category")
        verbose_name_plural = ("categories")

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse("post:post_list_view", args=[self.slug])



class Repair(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
path_and_rename = PathAndRename("posts")    
class Kvartera(models.Model):
    STATUS = (
        ('ha','ha'),
        ('yuq','yuq'),
    )
   
    # user = models.OneToOneField(Account,on_delete=models.CASCADE)
    image = models.ImageField(upload_to=path_and_rename, blank=True, null=True)
    title = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='title', unique=True)
    category = models.ForeignKey(Category,on_delete=models.CASCADE)
    description = models.TextField()
    price = models.IntegerField()
    number_rooms = models.IntegerField()
    total_area = models.IntegerField()
    living_space = models.IntegerField()
    kitchen_area = models.PositiveIntegerField()
    floor = models.PositiveIntegerField()
    house_floor_plan = models.PositiveIntegerField()
    is_available = models.BooleanField(default=True, help_text="Is product available?")
    addrees = models.TextField()
    # year_of_construction = models.DateField()
    # furniture = models.CharField(max_length=50,choices=STATUS)
    # repair = models.ForeignKey(Repair,on_delete=models.CASCADE)
    vositachilik_haqi = models.CharField(max_length=100,choices=STATUS)
    

    class Meta:
        verbose_name = ("kvartera")
        verbose_name_plural = ("kvarteras")

    def __str__(self):
        return self.title
    
    
    def get_absolute_url(self):
        return reverse("post:post_detail_view", args=[self.category.slug, self.slug])

    def get_image_url(self):
        return self.image.url if self.image and hasattr(self.image, "url") else "#"

class StudentWork(models.Model):
    image = models.ImageField(upload_to='kvartera')
    title = models.CharField(max_length=100)
    slug = AutoSlugField(populate_from='title', unique=True)
    description = models.TextField()
    price = models.IntegerField()
    addrees = models.TextField()
    is_available = models.BooleanField(default=True, help_text="Is product available?")
   

    class Meta:
        verbose_name = ("Student Work")
        verbose_name_plural = ("Student Works")

    def __str__(self):
        return self.title
    
    
    def get_absolute_url(self):
        return reverse("post:post_list_view", args=[self.category.slug, self.slug])

    def get_image_url(self):
        return self.image.url if self.image and hasattr(self.image, "url") else "#"

post/forms.py
from django import forms
from post.models import Kvartera
from django.forms import ModelForm
from django.forms import ModelChoiceField
from .models import Kvartera, Category

class KvarteraForm(forms.ModelForm):
    category = ModelChoiceField(queryset=Category.objects.all(), to_field_name='id')

    class Meta:
        model = Kvartera
        fields = "__all__"

    def clean(self):
        cleaned_data = super(KvarteraForm, self).clean()
    
    def __init__(self, *args, **kwargs):
        super(KvarteraForm, self).__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs["class"] = "form-control"

post/views.py
from django.shortcuts import render
from .forms import KvarteraForm
from django.shortcuts import redirect
from .models import Kvartera
def KvarteraView(request):
    if request.method == 'GET':
        form = KvarteraForm()
        return render(request, 'post/form.html', {'form': form})


        
    if request.method == 'POST':
        form = KvarteraForm(request.POST)
        if form.is_valid():
            # new_form = form.save(commit=False)
            price = request.POST['price']
            title = request.POST['title']
            b = Kvartera.objects.create(price=price, title=title)
            # price = form.cleaned_data.get('price')
            # title = form.cleaned_data.get('title')
            # new_form.price = price
            # new_form.title = title
            b.save()
            return redirect('account:hompage')
        else:
            return render(request, 'post/form.html', {'form': form})

def saveform(request):
    if request.POST:
        model = Kvartera()
        model.title = request.POST['title']
        model.price = request.POST['price']
        model.total_area = request.POST['total_area']
        model.description = request.POST['description']
        model.living_space = request.POST['living_space']
        model.number_rooms = request.POST['number_rooms']
        model.kitchen_area = request.POST['kitchen_area']
        model.floor = request.POST['floor']
        model.house_floor_plan = request.POST['house_floor_plan']
        # model.year_of_construction = request.POST['year_of_construction']
        print(request.POST.get('title'))
        
    
        model.save()    
        return redirect('account:homepage')
    return redirect("post:kvarteraview")
                

post/views/post.py
from django.shortcuts import render
from ..forms import KvarteraForm
from django.shortcuts import redirect
from ..models import Kvartera,Category
def KvarteraView(request):
    if request.method == 'GET':
        form = KvarteraForm()
        return render(request, 'post/form.html', {'form': form})


        
    if request.method == 'POST':
        form = KvarteraForm(request.POST)
        if form.is_valid():
            # new_form = form.save(commit=False)
            price = request.POST['price']
            title = request.POST['title']
            b = Kvartera.objects.create(price=price, title=title)
            # price = form.cleaned_data.get('price')
            # title = form.cleaned_data.get('title')
            # new_form.price = price
            # new_form.title = title
            b.save()
            return redirect('account:hompage')
        else:
            return render(request, 'post/form.html', {'form': form})

    
 

post/views/post_list.py
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from ..forms import KvarteraForm
from ..models import Category, Kvartera


def post_list_view(request, category_slug=None):
        posts = Kvartera.objects.filter(is_available=True)
        if category_slug:  
            category = Category.objects.get(slug=category_slug)
            posts = Kvartera.objects.filter(category=category, is_available=True)
        return render(request, "post/post.html", {"posts": posts,})
  

def post_detail_view(request, category_slug, product_slug):   
    post = Kvartera.objects.get(category__slug=category_slug, slug=product_slug)
    context = {
        "post": post,
    }
    return render(request, "post/post_detail.html", context)



def saveform(request):
    if request.POST:
        category_id = str(request.POST.get('category'))
        category = Category.objects.get(id=category_id)
        model = Kvartera()
        model.category = category
        model.title = request.POST['title']
        model.price = request.POST['price']
        model.image = request.POST['image']
        model.total_area = request.POST['total_area']
        model.description = request.POST['description']
        model.living_space = request.POST['living_space']
        model.number_rooms = request.POST['number_rooms']
        model.kitchen_area = request.POST['kitchen_area']
        model.floor = request.POST['floor']
        model.house_floor_plan = request.POST['house_floor_plan']
        model.vositachilik_haqi = request.POST['vositachilik_haqi']
        # model.year_of_construction = request.POST['year_of_construction']
        model.save()    
        return redirect('account:homepage')
    return redirect("post:kvarteraview")
 

templates/post/form.html
{% extends "base.html" %}
{% load static %}

{% block title %}

Register

{% endblock %}


{% block content %}



<!-- ========================= SECTION CONTENT ========================= -->
<section class="section-conten padding-y" style="min-height:84vh">



    <!-- ============================ COMPONENT LOGIN   ================================= -->
        <div class="card mx-auto" style="max-width: 800px; margin-top:100px;">


          {% include 'includes/message.html' %}


          <div class="card-body">
          <h4 class="card-title mb-8">Elon berish</h4>
          <form method="post" action="{% url 'post:saveform' %}">
            {% csrf_token %}
            <div class="row">
                          
                <div class="form-group col-sm-6">
                    <label>price</label>
                    {{form.price}}
                    {{form.price.errors}}
                </div>                
                <div class="form-group col-sm-6">
                    <label>image</label>
                    {{form.image}}
                    {{form.image.errors}}
                </div>       
                <div class="form-group col-sm-12">
                    <label>title</label>
                    {{form.title}}
                    {{form.title.errors}}
                </div>         
                <div class="form-group col-sm-12">
                    <label>category</label>
                    {{form.category}}
                    {{form.category.errors}}
                </div>   
                <div class="form-group col-sm-14">
                    <label>addrees</label>
                    {{form.addrees}}
                    {{form.addrees.errors}}
                </div>         
                <div class="form-group col-sm-14">
                    <label>description</label>
                    {{form.description}}
                    {{form.description.errors}}
                </div>         
                <div class="form-group col-sm-6">
                    <label>number_rooms</label>
                    {{form.number_rooms}}
                    {{form.number_rooms.errors}}
                </div>                
                <div class="form-group col-sm-6">
                    <label>total_area</label>
                    {{form.total_area}}
                    {{form.total_area.errors}}
                </div>                
                <div class="form-group col-sm-6">
                    <label>living_space</label>
                    {{form.living_space}}
                    {{form.living_space.errors}}
                </div>         
                <div class="form-group col-sm-6">
                    <label>kitchen_area</label>
                    {{form.kitchen_area}}
                    {{form.kitchen_area.errors}}
                </div>         
                <div class="form-group col-sm-6">
                    <label>floor</label>
                    {{form.floor}}
                    {{form.floor.errors}}
                </div>         
                <div class="form-group col-sm-6">
                    <label>house_floor_plan</label>
                    {{form.house_floor_plan}}
                    {{form.house_floor_plan.errors}}
                </div>         
                <div class="form-group col-sm-6">
                    <label>vositachilik_haqi</label>
                    {{form.vositachilik_haqi}}
                    {{form.vositachilik_haqi.errors}}
                </div>         


                <input type="submit" class="btn btn-primary btn-block" value="Add">

                
            </div> <!-- row.// -->	
        </form>
          </div> <!-- card-body.// -->
        </div> <!-- card .// -->
    
         
  
    </section>
   
{% endblock %} 

templates/post/post.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}

{% block title %}

Home

{% endblock %}


{% block content %}



<!-- ========================= SECTION PAGETOP ========================= -->
<section class="section-pagetop bg">
    <div class="container">
        <h2 class="title-page">Elonlar</h2>
        
    </div> <!-- container //  -->
    </section>
    <!-- ========================= SECTION INTRO END// ========================= -->
    
    <!-- ========================= SECTION CONTENT ========================= -->
    <section class="section-content padding-y">
    <div class="container">
    
    <div class="row">
        <aside class="col-md-3">
            
    <div class="card">
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_1" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Kvarteralar</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_1" style="">
                <div class="card-body">
                    
                    <ul class="list-menu">
                    {% for category in categories %}
                        <li><a href="{{category.get_absolute_url}}">{{ category.name }}</a></li>
                    {% endfor %}
                    </ul>
    
                </div> <!-- card-body.// -->
            </div>
        </article> <!-- filter-group  .// -->
        <article class="filter-group">
            
            </div>
        </article> <!-- filter-group .// -->
        
        <article class="filter-group">
            <header class="card-header">
                <a href="#" data-toggle="collapse" data-target="#collapse_3" aria-expanded="true" class="">
                    <i class="icon-control fa fa-chevron-down"></i>
                    <h6 class="title">Price range"</h6>
                </a>
            </header>
            <div class="filter-content collapse show" id="collapse_3" >
                <form method="get">
                <div class="card-body">

                        <div class="form-row">
                            <div class="form-group col-md-6">
                      <label>Min</label>
                      <!-- <input class="form-control" placeholder="$0" type="number"> -->
                          <select name="min" class="mr-2 form-control">
                            <option value="0">$0</option>
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                        </select>
                    </div>
                    <div class="form-group text-right col-md-6">
                      <label>Max</label>
                          <select name="max" class="mr-2 form-control">
                            <option value="50">$50</option>
                            <option value="100">$100</option>
                            <option value="150">$150</option>
                            <option value="200">$200</option>
                            <option value="500">$500</option>
                            <option value="1000">$1000</option>
                            <option value="2000">$2000+</option>
                        </select>
                    </div>
                </div> <!-- form-row.// -->
                <button class="btn btn-block btn-primary">Apply</button>
            </div><!-- card-body.// -->
        </form>
            </div>
        </article> <!-- filter-group .// -->
        
    </div> <!-- card.// -->
    
        </aside> <!-- col.// -->
        <main class="col-md-9">
    
    <header class="border-bottom mb-4 pb-3">
            <div class="form-inline">
                <span class="mr-md-auto">Items found!</span>
                
            </div>
    </header><!-- sect-heading -->
    
    <div class="row">

        {% for post in posts %}

        <div class="col-md-4">
            <figure class="card card-product-grid">
                <div class="img-wrap"> 
                    
                    <img  src="{{ post.get_image_url }}">

                    
                </div> <!-- img-wrap.// -->
                <figcaption class="info-wrap">
                    <div class="fix-height">
                        <a href="{{ post.get_absolute_url }}" class="title">{{ post.title }}</a>
                        <div class="price-wrap mt-2">
                            <span class="price">${{ post.price }}</span>
                            
                        </div> <!-- price-wrap.// -->
                    </div>
                    <a href="{{ post.get_absolute_url }}" class="btn btn-block btn-success">elonni ko'rish</a>
                </figcaption>
            </figure>
        </div> <!-- col.// -->
        {% endfor %}
        
    </div> <!-- row end.// -->
    
    
        </main> <!-- col.// -->
    
    </div>
    
    </div> <!-- container .//  -->
    </section>
  
        
{% endblock %} 

templates/post/post_detail.html
{% extends "base.html" %}
{% load static %}
{% block title %}
Home
{% endblock %}
{% block content %}

<link href="{% static 'css/rate.css' %}" rel="stylesheet" type="text/css"/>


<section class="section-content padding-y bg">
    <div class="container">
    
    <div class="card">
        <div class="row no-gutters">
            <aside class="col-md-6">
                <article class="gallery-wrap"> 
                    <div class="img-big-wrap mainImage">
                    {% if product.image %}
                        <a href="{{ post.get_image_url}}"><img src="{{ post.get_image_url}}" alt="Product Picture"></a>
                    {% else %}
                        <a href="{% static 'images/no-image.png' %}"><img src="{% static 'images/no-image.png' %}" alt="Product Picture"></a>
                    {% endif %}
                    </div> 
                    
                </article> 
            </aside>
    <main class="col-md-6 border-left">
    <article class="content-body">
    
    <h2 class="title">{{post.title}}  </h2>

    <div class="mb-3"> 
        <var class="price h4">{{ post.price }}$</var> 
    </div> 
    <p>
        {{ post.description }} <br/>
        uy raqami: {{ post.number_rooms }} umumiy maydon: {{post.total_area }}
        yashash  maydon:{{post.living_space}} <br/>
        oshxona maydoni:{{post.kitchen_area}}
        qavati:{{post.floor}}
         uy qavatliligi:{{post.house_floor_plan}}
    </p>    

    <button type="submit" class="btn  btn-primary"> <span class="text">xabar junatish</span> <i class="fa-solid fa-messages fa-beat" style="color: #d6f109;"></i>  </button>
    <button type="submit" class="btn  btn-primary"> <span class="text">Qo'ng'iroq qilish</span> <i class="fa-sharp fa-solid fa-phone fa-bounce" style="color: #d8f40b;"></i></i>  </button> 
    </form>    
    </section>
{% endblock %} 